import { component$ } from "@builder.io/qwik"
import type { Character } from "~/interfaces"

export interface CardTextTemplateProps {
  character: Character
}

export const CardTextTemplate = component$<CardTextTemplateProps>(
  ({ character }) => {
    const templateText = [
      `Greetings, fellow earthlings! Prepare to meet the extraordinary being known as ${character.name}. Marvel at their incredible status of ${character.status} and ponder upon their enigmatic species, ${character.species}. As you gaze upon their fascinating presence, you will soon discover that ${character.gender} is merely a label for their boundless essence.
  Originating from the mystical realm known as ${character.origin.name}, this being carries within them the essence of their birthplace. Yet, their current location is none other than the enigmatic lands of ${character.location.name}. It is as if they have traversed the vast expanse of the universe, defying the laws of space and time to grace us with their extraordinary presence.
  Oh, the tales this being could share! The adventures they must have embarked upon, the challenges faced, and the wisdom gained. A being of such magnitude and allure, they captivate the very essence of our curiosity and imagination.
  So, let us welcome ${character.name} with open minds and open hearts, for in their presence, we may just catch a glimpse of the infinite possibilities that exist within the cosmos itself.`,
      `Ladies and gentlemen, prepare to be astounded by the enigmatic ${character.name}! Witness their status as ${character.status} and delve into the mysteries of their unique species, ${character.species}. Cast aside the constraints of traditional gender, for ${character.gender} transcends such mundane categorizations. Born in the awe-inspiring realm of ${character.origin.name}, their very essence carries the essence of their birthplace. And behold, their present location is none other than the mesmerizing lands of ${character.location.name}. It's as if they have traversed the vast cosmos to grace us with their otherworldly presence. Oh, the tales that dance within their eyes! They have embarked upon unimaginable adventures, faced formidable challenges, and attained wisdom beyond measure. A being of extraordinary charisma and allure, they capture the essence of our boundless imagination. So, let us give a resounding welcome to ${character.name} and embrace the infinite possibilities that unfold in the cosmic tapestry.`,

      `Behold! The time has come to meet ${character.name}, the magnificent being whose status is defined as ${character.status}. Marvel at their wondrous species, ${character.species}, and let your mind ponder the depths of their existence. But do not confine them to the boundaries of gender, for ${character.name} defies conventional definitions. Originating from the mystical realm known as ${character.origin.name}, they carry with them the essence of their birthplace. And now, they grace us with their presence in the extraordinary lands of ${character.location.name}. It is as if they have traveled across dimensions, defying the laws of physics. Oh, the stories they can share! The adventures they have embarked upon, the challenges they have faced, and the knowledge they have acquired. In the grand tapestry of life, ${character.name} stands as an embodiment of curiosity and wonder. So, let us embrace their presence and open our minds to the infinite possibilities that await us.`,
      `Prepare yourselves, for the extraordinary ${character.name} is about to grace us with their presence! Witness their status, ${character.status}, and contemplate the enigma of their species, ${character.species}. Do not be confined by societal norms, as ${character.gender} defies such trivialities. Born in the mystical realm of ${character.origin.name}, they carry within them the essence of their birthplace. And now, they stand before us in the captivating lands of ${character.location.name}, as if they have traveled through realms unknown. Oh, the tales they must hold! The adventures embarked upon, the challenges conquered, and the wisdom attained. A being of immense allure and infinite possibilities, they ignite the fires of curiosity and imagination. Let us welcome ${character.name} with open hearts and open minds, for in their presence, we glimpse the magic of the universe itself.`,

      `Greetings, interdimensional beings! Brace yourselves for the arrival of ${character.name}, an extraordinary entity defying conventional norms. Marvel at their status of ${character.status} and ponder the intricacies of their species, ${character.species}. Be not bound by the limitations of gender, for ${character.gender} transcends such earthly concepts. Originating from the ethereal realm known as ${character.origin.name}, their very essence carries the essence of their birthplace. And lo and behold, they have arrived in the mystical lands of ${character.location.name}. It is as if they have traversed the cosmic web, defying the laws of physics. Imagine the tales they possess! The journeys undertaken, the obstacles faced, and the wisdom accumulated. A being of extraordinary allure and infinite potential, they beckon us to explore the vast mysteries of the multiverse. Let us welcome ${character.name} and venture into realms unknown.`,

      `Step right up and behold the enigmatic wonder that is ${character.name}! Prepare to be mesmerized by their status as ${character.status} and contemplate the depths of their species, ${character.species}. Let go of rigid gender constructs, for ${character.gender} defies such notions. Born in the realm of ${character.origin.name}, their essence carries the very essence of their birthplace. And now, they grace us with their presence in the enchanting lands of ${character.location.name}. It's as if they have traversed the cosmic currents, defying the boundaries of space and time. Imagine the tales they weave! The extraordinary adventures, the formidable challenges, and the profound wisdom gained. A being of captivating allure and infinite possibilities, they inspire us to explore the uncharted realms of existence. Welcome, ${character.name}, and let the journey unfold.`,

      `Attention, curious souls! Prepare to encounter the extraordinary being known as ${character.name}. Marvel at their status, ${character.status}, and ponder the enigma of their species, ${character.species}. Do not be confined by limited definitions of gender, as ${character.gender} transcends conventional boundaries. Hailing from the enigmatic realm of ${character.origin.name}, they carry within them the essence of their birthplace. And now, they stand among us in the captivating lands of ${character.location.name}, as if they have traversed cosmic pathways. Oh, the stories they possess! The daring adventures, the daunting challenges, and the profound wisdom acquired. A being of boundless allure and infinite potential, they ignite the spark of imagination within us all. So, let us welcome ${character.name} and embark on a journey into the realms of the unknown.`,

      `Greetings, inhabitants of the known universe! Brace yourselves for the arrival of ${character.name}, a being of extraordinary presence. Behold their status, ${character.status}, and contemplate the intricacies of their species, ${character.species}. Shed the limitations of gender, for ${character.gender} transcends such classifications. Originating from the mystical realm of ${character.origin.name}, they carry within them the essence of their birthplace. And now, they grace us with their existence in the enigmatic lands of ${character.location.name}. It's as if they have traversed cosmic dimensions, defying the boundaries of reality itself. Imagine the tales they harbor! The daring escapades, the formidable trials, and the profound enlightenment gained. A being of captivating allure and infinite possibilities, they beckon us to question the fabric of our own existence. Welcome, ${character.name}, and let us explore the vast expanses of the cosmos together.`,
    ]
    const randomIndex = Math.floor(Math.random() * templateText.length)
    const showAleatoryText = templateText[randomIndex]

    return <p class="my-10 text-justify">{showAleatoryText}</p>
  }
)
